
export const UNITED_STATES = "United States";

export const COUNTRIES = ["", UNITED_STATES, "Afghanistan", "Akrotiri", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Ashmore and Cartier Islands", "Australia", "Austria", "Azerbaijan", "Bahamas, The", "Bahrain", "Bangladesh", "Barbados", "Bassas da India", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Clipperton Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Cook Islands", "Coral Sea Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Dhekelia", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Europa Island", "Falkland Islands (Islas Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern and Antarctic Lands", "Gabon", "Gambia, The", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Glorioso Islands", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands", "Holy See (Vatican City)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Jan Mayen", "Japan", "Jersey", "Jordan", "Juan de Nova Island", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Namibia", "Nauru", "Navassa Island", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paracel Islands", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russia", "Rwanda", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia and Montenegro", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "Spain", "Spratly Islands", "Sri Lanka", "Sudan", "Suriname", "Svalbard", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tromelin Island", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands", "Wake Island", "Wallis and Futuna", "West Bank", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"]

export const STATES =["Alaska",
                  "Alabama",
                  "Arkansas",
                  "American Samoa",
                  "Arizona",
                  "California",
                  "Colorado",
                  "Connecticut",
                  "District of Columbia",
                  "Delaware",
                  "Florida",
                  "Georgia",
                  "Guam",
                  "Hawaii",
                  "Iowa",
                  "Idaho",
                  "Illinois",
                  "Indiana",
                  "Kansas",
                  "Kentucky",
                  "Louisiana",
                  "Massachusetts",
                  "Maryland",
                  "Maine",
                  "Michigan",
                  "Minnesota",
                  "Missouri",
                  "Mississippi",
                  "Montana",
                  "North Carolina",
                  " North Dakota",
                  "Nebraska",
                  "New Hampshire",
                  "New Jersey",
                  "New Mexico",
                  "Nevada",
                  "New York",
                  "Ohio",
                  "Oklahoma",
                  "Oregon",
                  "Pennsylvania",
                  "Puerto Rico",
                  "Rhode Island",
                  "South Carolina",
                  "South Dakota",
                  "Tennessee",
                  "Texas",
                  "Utah",
                  "Virginia",
                  "Virgin Islands",
                  "Vermont",
                  "Washington",
                  "Wisconsin",
                  "West Virginia",
                  "Wyoming"];

export const COURSE_LIST = ["", 
"1. A Brief Introduction to the Contemporary Politics of the Middle East",
"2. A Brief Tour of the Stratosphere",
"3. A Cappella 101: Making Music with the Human Voice",
"4. A Taste of Culinary Diplomacy",
"5. Abnormal Psychology ",
"6. Accepted or Rejected? Tackling College Admissions",
"7. Alzheimer's: It's more than forgetting! ",
"8. An Introduction to Special Relativity",
"10. Analyzing Companies through Accounting",
"11. Applied Physics: A Matter of looking at the world",
"12. Around the World through Film",
"13. Bio Detectives: Unwinding a Trauma Case",
"14. Calligraphy 101",
"15. Chemophobia: What's a Chemical? ",
"16. Chuck Chiquita: Delving into the Questionable Ethics of the Banana Tycoon",
"17. Code with Code",
"18. Computer Science and Self Driving Cars",
"19. Counting Infinities",
"20. Cracking university essays (US&UK) + How to effectively analyse different texts types",
"21. Crafting, Card Making, Journaling",
"22. Crash Course of the Israeli-Palestinian Conflict",
"23. Crossword Construction",
"24. Data Analysis and Web Apps in R Shiny",
"25. Designing the toys of the future",
"26. Digital Art: Re-Coloring the Screen",
"27. DNA and Genomes",
"28. Do We Have Free Will? Why Does it Matter?",
"29. Energy Resources, Impacts, and the Environment",
"30. Everything you wanted to know about being a scientist, but were too afraid to ask ",
"31. Exploring the Human Brain",
"32. Feminism, Murder, and Madness: Reading “Macbeth” in 2020",
"33. Financeverse",
"34. From Colonialism to Coronavirus: Issues in Global Health ",
"35. From the Torah to Today: The Jewish History They Don't Teach You In School",
"36. Fun with French",
"37. Fundamentals of Investing",
"38. Geometry (High School Level)",
"39. Harry Potter and Latin: Ancient References in the Harry Potter Series",
"40. History of Medicine in the Middle Ages and Renaissance",
"41. History of Modern Art",
"42. How Cancer Works",
"43. How Languages Change",
"44. How to Play Chess",
"45. How to Prove Things: Number Theory",
"46. Human Behavior: From Salem Witch Trials to Mass Shootings",
"47. I NEED TO GET INTO COLLEGE...SEND HELP",
"48. Intro to AP Physics 1",
"49. Intro to Astronomy: the Solar System",
"50. Intro to Calculus: Derivatives and Their Applications",
"51. Intro to Irish Mythology",
"52. Intro to Photography",
"53. Introduction to Algorithmic Thinking",
"54. Introduction to Algothrithms",
"55. Introduction to Body Systems",
"56. Intro to C++",
"57. Introduction to Calculus",
"58. Introduction to Computational Physics",
"59. Introduction to Creation Myths",
"60. Introduction to Due Process in the United States",
"61. Introduction to Earthquake Science",
"62. Introduction to Effective and Persuasive Debate",
"63. Introduction to Environmental Science",
"64. Introduction to Fundamentals of General Chemistry",
"65. Introduction to Geometry",
"66. Introduction to Green Building",
"67. Introduction to Java: Theory and Programming",
"68. Introduction to Machine Learning and Data Science",
"69. Introduction to Rule-Based Art (Open Studio Class)",
"70. Introduction to Solar Fuels",
"71. Introduction to Speech and Debate",
"124. Introduction to the Four Time Periods of Classical Music",
"72. Introduction to The Great Gatsby ",
"73. Israel Life/History/Culture",
"74. Junior Medical Academy- Medical Biotechnology",
"75. Leadership in Model United Nations ",
"76. Legacies of Colonialism: Contemporary Central African History",
"77. Let's rethink the way we think about stress- How to be happy with yourself and work well with others!",
"78. Life Interrupted: The Impacts of Concussion on the Brain",
"79. Linguistic Archaeology",
"80. Listen Up! The Science of Hearing",
"81. Logic, An Introduction",
"82. Logic and Mathematics",
"83. Our Planet is Dying. ",
"84. Personal Finance 101",
"85. People, Profits, and the Planet: An Introduction to the Circular Economy",
"86. Physics: But make it fast",
"87. Physics: Introduction to Mechanics",
"88. Pixar's 5 Life Lessons",
"89. Political Theory and its Application in Contemporary Society",
"90. Quantum Computing",
"91. Racist America And How We Got Here",
"92. Scheduling Happiness",
"93. Secondhand Spaniard: learn basic Spanish",
"94. Social Media and Society",
"95. Social Psychology and the American Criminal Justice System",
"96. Somehow I Manage: Introduction to Management and Business Studies",
"97. Tennis at Home!",
"98. The Amazing World of Computers",
"99. The Art of Laughs: Writing Your First Stand-Up Comedy Set",
"100. The Art of Math Proof-Writing and Unproven Mysteries",
"101. The Art of Public Speaking: An Introduction",
"102. The Basics of Financial Literacy: Shaping Your Financial Future ",
"103. The Coolest Musicians You've Never Heard Of",
"104. The DSM-V & its troubles: what it is, how it works, and what it leaves out",
"105. The Etruscan Civilisation: Founding Fathers of Rome",
"107. The Evolution of Memes: Origins to Contemporary Politics",
"108. The Generation of Change",
"109. The ice caps are melting, so what? An Intro to Intersectional Environmentalism",
"110. The Placebo Effect",
"111. The Theory of Special Relativity",
"112. Time Management (Grades 6-8)",
"113. Time Management (Grades 9-12)",
"114. To Hand and Back: How to Juggle, and Why",
"115. Understanding Bitcoin, Ethereum and Mining",
"116. Understanding the World of Special Needs",
"117. Understanding U.S. Foreign Affairs",
"118. Visual Thinking and Fractal Gridding: Tools for Learning in a New Light",
"119. Wall Street 101: Economics",
"120. What is CBD?",
"121. What is Nursing? A Comprehensive Guide for High Schoolers",
"122. What Your High School Government Classes Won't Teach You",
"123. Who Did It? Forensic Analysis and Culprit Identification"];
