
export const UNITED_STATES = "United States";

export const COUNTRIES = ["", UNITED_STATES, "Afghanistan", "Akrotiri", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Ashmore and Cartier Islands", "Australia", "Austria", "Azerbaijan", "Bahamas, The", "Bahrain", "Bangladesh", "Barbados", "Bassas da India", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Clipperton Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Cook Islands", "Coral Sea Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Dhekelia", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Europa Island", "Falkland Islands (Islas Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern and Antarctic Lands", "Gabon", "Gambia, The", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Glorioso Islands", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands", "Holy See (Vatican City)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Jan Mayen", "Japan", "Jersey", "Jordan", "Juan de Nova Island", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Namibia", "Nauru", "Navassa Island", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paracel Islands", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russia", "Rwanda", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia and Montenegro", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "Spain", "Spratly Islands", "Sri Lanka", "Sudan", "Suriname", "Svalbard", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tromelin Island", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands", "Wake Island", "Wallis and Futuna", "West Bank", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"]

export const STATES =["Alaska",
                  "Alabama",
                  "Arkansas",
                  "American Samoa",
                  "Arizona",
                  "California",
                  "Colorado",
                  "Connecticut",
                  "District of Columbia",
                  "Delaware",
                  "Florida",
                  "Georgia",
                  "Guam",
                  "Hawaii",
                  "Iowa",
                  "Idaho",
                  "Illinois",
                  "Indiana",
                  "Kansas",
                  "Kentucky",
                  "Louisiana",
                  "Massachusetts",
                  "Maryland",
                  "Maine",
                  "Michigan",
                  "Minnesota",
                  "Missouri",
                  "Mississippi",
                  "Montana",
                  "North Carolina",
                  " North Dakota",
                  "Nebraska",
                  "New Hampshire",
                  "New Jersey",
                  "New Mexico",
                  "Nevada",
                  "New York",
                  "Ohio",
                  "Oklahoma",
                  "Oregon",
                  "Pennsylvania",
                  "Puerto Rico",
                  "Rhode Island",
                  "South Carolina",
                  "South Dakota",
                  "Tennessee",
                  "Texas",
                  "Utah",
                  "Virginia",
                  "Virgin Islands",
                  "Vermont",
                  "Washington",
                  "Wisconsin",
                  "West Virginia",
                  "Wyoming"];

export const COURSE_LIST = ["", "1. A History of the World in Six Drinks",
"2. Abnormal Psychology (ONLY Grades 9-12)",
"3. Accepted or Rejected? Tackling College Admissions (ONLY Grades 10-12)",
"4. An Introduction to Film Analysis",
"5. An Introduction to Music Theory",
"6. Analyzing Film",
"7. Architectural Masterpieces in Western History (ONLY Grades 8-12)",
"8. Art of the Personal Essay: A Dive into Creative Nonfiction",
"9. Art School Portfolio Development ",
"10. Artificial Intelligence and Ethics",
"11. Artificial Intelligence and Machine Learning with Python",
"12. ASL Basics Continued",
"13. Bacteria, Viruses, and the Immune System",
"15. Building Healthy Habits",
"16. Building Your Own Nonprofit (ONLY Grades 8-12)",
"17. Calculus and Beyond: Topics in Math Theory and Applications (ONLY Grades 8-12)",
"18. Campaigns and Elections 101",
"19. Chinese Customs & Culture",
"20. Classical Music Since You Were Born",
"21. Clinical Psych-Up (ONLY Grades 9-12)",
"22. Connecting Algebraic Principles to Algebra I",
"23. Controversial Clinical and Psychological Studies that Changed our Understanding of Humans (ONLY Grades 9-12)",
"24. Counting Infinities",
"25. Crash Course of the Israeli-Palestinian Conflict",
"26. Creating your Graphic Novel",
"27. Data Analysis with Python",
"28. Debate and Philosophy: An Introduction",
"29. Drugs and Neurotransmission",
"30. Energy Resources, Impacts, and the Environment",
"31. Ethics: Navigating Right and Wrong (ONLY Grades 10-12)",
"32. Exploring Genetics in Different Contexts  ",
"33. French (for beginners, intermediate or advanced)",
"34. Fun with French",
"35. Game Theory",
"36. Gravitational Waves (ONLY Grades 9-12)",
"37. Greek Mythology & Modern Day Storytelling",
"38. Guilty as Charged: An Overview of the American Legal System",
"39. Harry Potter and Latin: Ancient References in the Harry Potter Series",
"40. History of Western Cinema",
"41. How the Arab Spring Shook the Middle East",
"42. How to Apply to College (ONLY Grades 11-12)",
"43. Human Behavior: From Salem Witch Trials to Mass Shootings (ONLY Grades 9-12)",
"44. Immersive Storytelling with VR for Social Impact (ONLY Grades 8-12)",
"45. Intro into MATLAB",
"46. Intro to C++",
"47. Intro to Calculus: Derivatives and their Applications (ONLY Grades 9-12)",
"48. Intro to Creative Writing: Exploring Poetry (ONLY Grades 8-11)",
"49. Intro to Neuroscience: Mind, Brain and Behavior",
"50. Intro to Social Psychology: Mind and Behavior (ONLY Grades 7-9)",
"51. Introduction to Algorithmic Thinking",
"52. Introduction to American Democracy",
"53. Introduction to Biology",
"54. Introduction to Body Systems (ONLY Grades 8-11)",
"55. Introduction to Economics",
"56. Introduction to Effective and Persuasive Debate (ONLY Grades 7-10)",
"57. Introduction to Green Building",
"58. Introduction to Java Game Development ",
"59. Introduction to Machine Learning",
"60. Introduction to the Four Time Periods of Classical Music",
"61. Introduction to Website Development: A Beginner’s Guide to HTML, CSS, and JS",
"62. Introduction to Writing Poetry ",
"63. Introductory Psychology",
"64. Jump Into the World of Business & Marketing",
"65. LabVIEW Programming",
"66. Legacies of Colonialism: Contemporary Central African History (ONLY Grades 9-12)",
"67. LGBTQ+ History and Why It Matters",
"68. Listen Up! The Science of Hearing",
"69. Mathematics",
"70. Mindful Tech Use in the Lockdown Age (ONLY Grades 9-12)",
"71. Mission: Climate",
"72. National Park Service 101",
"73. One Show More: Exploring Musical Theatre Through Literary Analysis",
"74. Origins of Physics and Quantitative Thinking",
"75. People, Profits, and the Planet: An Introduction to the Circular Economy",
"76. Personal Essays and Owning the Prompt (ONLY Grades 10-12)",
"77. Satire Writing (ONLY Grades 10-12)",
"78. Smart Sheep: Human Rights through Consumerism ",
"79. Speaking from the Heart ",
"80. Sports: Movements and Justice",
"81. Stem Cell Biology and Ethics",
"82. Taiwan 101",
"83. Tennis At Home! (ONLY Grades 6-8)",
"84. The American People's History: A Look at Race in America",
"85. The Art of Math Logic",
"86. The Basics of Blockchain (featuring JavaScript)",
"87. The Causes and Impacts of the COVID-19 Pandemic (ONLY Grades 9-12)",
"88. The Complexity of Cancer",
"89. The Coolest Musicians You've Never Heard of",
"90. The Cultural Impacts of Sitcoms",
"91. The Evolution and Impact of Imperialism: East Asia",
"92. The Fantastical in the Mundane: Reading & Writing Magical Realism (ONLY Grades 8-12)",
"93. The Freakiest Waves at the Wave Festival: A Fourth Dimensional Look into Gravitational Waves and Relativity Theory",
"94. The ice caps are melting, so what? An Introduction to Intersectional Environmentalism ",
"95. The Tips & Secrets, the Do's & Don'ts for High School (ONLY Grades 9-12)",
"96. Thinking Visual (ONLY Grades 7-9)",
"97. Thinking with Physics",
"98. Ticket to Foreign Policy: Intro to Field Research",
"99. Time is Money",
"100. To Hand and Back: How To Juggle, and Why",
"101. Topics in Genetics",
"102. Understanding Political Manipulation",
"103. Understanding the Mind & The Limits of A.I.",
"104. Venture Capital: The other side of starting a business (ONLY Grades 11-12)",
"105. Visual Thinking and Fractal Gridding: Tools for Learning in a New Light (ONLY Grades 9-12)",
"106. Wall Street 101: Economics (ONLY Grades 9-12)",
"107. Water, Chemicals and more with Computers for Chemistry",
"108. Writers' Workshop: Intro to Fiction Writing (ONLY Grades 7-9)"];
